### ISSUE TITLE
Ruby 2.5 support?

### ISSUE THREAD

**Issue by rpbaltazar** [dtaniwaki/paperclip-deflater#14]
Gemspec on release 0.1.4 establishes that ruby 2.5 would be supported, but this is restricted in 0.1.5.

Is Ruby 2.5 supported after all?

**Comment by dtaniwaki** [comment]
I released [v0.1.6](https://github.com/dtaniwaki/paperclip-deflater/releases/tag/v0.1.6) with Ruby 2.5 support. 👍
